name: stock-analysis
channels:
  - jholdom
  - defaults
dependencies:
  - apscheduler=3.6.3
  - astroid=2.4.2
  - beautifulsoup4=4.9.1
  - blas=1.0
  - brotlipy=0.7.0
  - ca-certificates=2020.10.14
  - certifi=2020.6.20
  - cffi=1.14.3
  - chardet=3.0.4
  - colorama=0.4.4
  - cryptography=3.1.1
  - cycler=0.10.0
  - freetype=2.10.4
  - html5lib=1.1
  - icu=58.2
  - idna=2.10
  - intel-openmp=2020.2
  - isort=5.6.4
  - jpeg=9b
  - kiwisolver=1.3.0
  - lazy-object-proxy=1.4.3
  - libiconv=1.15
  - libpng=1.6.37
  - libtiff=4.1.0
  - libxml2=2.9.10
  - libxslt=1.1.34
  - lxml=4.6.1
  - lz4-c=1.9.2
  - matplotlib=3.3.1
  - matplotlib-base=3.3.1
  - mccabe=0.6.1
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1h
  - pandas=1.1.1
  - pandas-datareader=0.9.0
  - pillow=8.0.1
  - pip=20.2.4
  - pycparser=2.20
  - pylint=2.6.0
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pysocks=1.7.1
  - python=3.6.5
  - python-dateutil=2.8.1
  - pytz=2020.1
  - qt=5.9.7
  - requests=2.24.0
  - schedule=0.5.0
  - selenium=3.141.0
  - setuptools=50.3.0
  - sip=4.19.8
  - six=1.15.0
  - soupsieve=2.0.1
  - sqlalchemy=1.3.19
  - sqlite=3.33.0
  - tk=8.6.10
  - toml=0.10.1
  - tornado=6.0.4
  - typed-ast=1.4.1
  - tzlocal=2.1
  - urllib3=1.25.11
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - webencodings=0.5.1
  - wheel=0.35.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - wrapt=1.11.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - brotli==1.0.9
    - click==7.1.2
    - dash==1.17.0
    - dash-bootstrap-components==0.10.7
    - dash-core-components==1.13.0
    - dash-html-components==1.1.1
    - dash-renderer==1.8.3
    - dash-table==4.11.0
    - dash-table-experiments==0.6.0
    - flask==1.1.2
    - flask-compress==1.8.0
    - Flask-Caching==1.9.0
    - future==0.18.2
    - itsdangerous==1.1.0
    - jinja2==2.11.2
    - markupsafe==1.1.1
    - pandas-ta==0.1.66b0
    - plotly==4.12.0
    - retrying==1.3.3
    - werkzeug==1.0.1
